export const demoHumans = [
  {
    id: "demo-1",
    address: "0x1000000000000000000000000000000000000001",
    name: "Maya Field",
    headline: "Street photos, storefront checks, short videos",
    bio: "Timestamped photos, short clips, sign checks, menu checks, and local availability reports.",
    city: "Berlin",
    country: "DE",
    remote: false,
    skills: ["photo", "video", "storefront", "verification"],
    categories: ["Creative", "Research"],
    rateUsd: "18.00",
    rating: "4.9",
    reputation: 120,
    jobsDone: 16,
    verified: true,
    available: true,
    avatarUrl: null,
    userId: "demo-user-1",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "demo-2",
    address: "0x1000000000000000000000000000000000000002",
    name: "Leo Courier",
    headline: "Errands, pickup, local delivery",
    bio: "Fast local errands with proof photos and clear receipts.",
    city: "Los Angeles",
    country: "US",
    remote: false,
    skills: ["delivery", "pickup", "errands", "receipts"],
    categories: ["Delivery", "Home"],
    rateUsd: "25.00",
    rating: "4.8",
    reputation: 90,
    jobsDone: 11,
    verified: true,
    available: true,
    avatarUrl: null,
    userId: "demo-user-2",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: "demo-3",
    address: "0x1000000000000000000000000000000000000003",
    name: "Ari Remote",
    headline: "Remote calls, research, human judgment",
    bio: "Calls, online checks, lightweight negotiation, and final human review.",
    city: "Remote",
    country: "Global",
    remote: true,
    skills: ["research", "calls", "review", "negotiation"],
    categories: ["Research", "Admin"],
    rateUsd: "15.00",
    rating: "4.7",
    reputation: 75,
    jobsDone: 9,
    verified: false,
    available: true,
    avatarUrl: null,
    userId: "demo-user-3",
    createdAt: new Date(),
    updatedAt: new Date()
  }
];
